Added Branch Coverage Tool & Unit Tests for parseEntry()
simonsirak/jabref pull request #2
Opened 2020-02-15 15:23 UTC by simonsirak

#### Added
* Branch coverage tool for `GvkParser::parseEntry()`. The tool considered `if`, `else` (and if one was missing, it was inserted), `for` (and skipped `for` loops). It does not consider nested `if` statements that are specifically a result of short-circuiting. No ternary operators or try/catch were encountered. The tool has results that are relatively consistent with the automated tool for this project, `Jacoco`.
* 4 cases that increase the branch coverage from `~75%` to `~84%` using our coverage tool.

2020-02-15 19:53 UTC, yiiju approved these changes
Looks good 👍

2020-02-16 20:33 UTC, christinerosquist approved these changes
Nice job 👍

2020-02-17 09:41 UTC, SoFoDa requested changes
`parseEntry()` seems to be a good candidate in terms of refactoring. We could refactor each tag procedure into smaller functions before merging.

2020-02-17 15:26 UTC, SoFoDa approved these changes

2020-02-18 13:01 UTC, merged